- name: Set facts for client
  set_fact:
    domains: []
    client_fqdn: "{{ inventory_hostname }}"

- name: Create /enrollment directory
  file:
    path: /enrollment
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Join IPA domain
  ansible.builtin.include_tasks:
    file: enroll_IPA.yml
  when:
  - '"ipa" in groups and groups["ipa"]'
  - join_ipa

- name: Stop SSSD
  service:
    name: sssd.service
    enabled: yes
    state: stopped

- name: Create /etc/sssd/sssd.conf
  template:
    src: sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: Create /etc/krb5.conf
  template:
    src: krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Set SELinux label for /enrollment
  shell: |
    if selinuxenabled; then
      semanage fcontext -a -t etc_t "/enrollment(/.*)*"
      restorecon -R -v /enrollment
    else
      exit 0
    fi

- name: Show configured domains
  debug:
    msg: "domains = {{ ', '.join(domains) }}"
