services:
  dns:
    image: localhost/sssd/ci-dns:latest
    container_name: sssd-wip-dns
  ipa:
    image: localhost/sssd/ci-base-ipa:${TAG}
    container_name: sssd-wip-ipa
  client:
    image: localhost/sssd/ci-base-client:${TAG}
    container_name: sssd-wip-client
