all:
  children:
    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3
    base:
      children:
        base_client:
          hosts:
            base-client
        base_ipa:
          hosts:
            base-ipa
      vars:
        ansible_connection: podman
        ansible_host: sssd-wip-base
        ansible_python_interpreter: /usr/bin/python3
        extended_packageset: yes
    services:
      children:
        client:
          hosts:
            client.test:
              ansible_host: sssd-wip-client
        ipa:
          hosts:
            master.ipa.test:
              ansible_host: sssd-wip-ipa
      vars:
        ansible_connection: podman
        ansible_python_interpreter: /usr/bin/python3
