---
- hosts: all
  gather_facts: yes
  roles:
  - dns

- name: Include base
  ansible.builtin.import_playbook: playbook_image_base.yml
  vars:
    passkey_support: "{{ override_passkey_support | default('no') | bool }}"
    user_regular_uid: 1024
    ansible_become: yes
    extended_packageset: "{{ override_extended_packageset | default('no') | bool }}"

- name: Include services
  ansible.builtin.import_playbook: playbook_image_service.yml
  vars:
    passkey_support: "{{ override_passkey_support | default('no') | bool }}"
    user_regular_uid: 1024
    ansible_become: yes
    join_ipa: "{{ override_join_ipa | default('yes') | bool }}"
    extended_packageset: "{{ override_extended_packageset | default('no') | bool }}"
