---
- hosts: services
  gather_facts: yes
  roles:
  - facts
  - firewall
  - no_nscd

- hosts: master.ipa.test
  gather_facts: no
  roles:
  - ipa
  - { role: passkey, when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" }

- hosts: client.ipa.test
  gather_facts: no
  roles:
  - client
  - { role: passkey, when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" }

- hosts: services
  gather_facts: no
  roles:
  - ssh_server
  - cleanup
